---
- name: install vsftpd
  hosts: rocky
  tasks:
  - name: install vsftpd 
    package:
      name: vsftpd
      state: present
  - name: start and enable vsftpd
    service:
      name: vsftpd
      state: started
      enabled: yes
  - name: install firewalld
    package:
      name: firewalld
      state: present
  - name: start firewalld
    service:
      name: firewalld
      state: started
      enabled: yes
  - name: open port in firewall
    firewalld:
      service: ftp
      permanent: yes
      state: enabled
      immediate: yes
