---
- name: install start and enable httpd
  gather_facts: false
  hosts: rocky
  tasks:
  - name: install package
    package:
      name: 
        - httpd
        - nftables
        - python3-firewall
      state: latest
  - name: start and enable firewalld
    service:
      name: firewalld
      state: started
      enabled: yes
  - name: start and enable httpd
    service:
      name: httpd
      state: started
      enabled: yes
 
  - name: open port in firewall
    firewalld:
      service: http
      permanent: yes
      state: enabled
      immediate: yes

- name: test httpd accessibility
  become: False
  gather_facts: no
  hosts: localhost
  tasks:
  - name: test httpd access
    uri:
      url: http://localhost
