---
- name: install nginx
  hosts: all
  pre_tasks:
  - block:
    - name: remove apache
      service:
        name: httpd
        state: stopped
        enabled: no
    - yum:
        name: httpd
        state: absent
    - name: perform package update
      yum:
        name: '*'
        state: latest 
    when: 
    - ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'Rocky'
  roles:
  - geerlingguy.nginx

  post_tasks:
  - file: 
      path: /var/cache/dnf
      state: absent
