---
- name: test command output
  hosts: ansible-node-01.deldel.lan
  tasks:
    - name: test for VG existence
      command: vgs rl
      register: vgout
      ignore_errors: True
    - name: show variable value
      debug:
        var: vgout
    - name: print message
      debug:
        msg: vg does not exist
      when: vgout["failed"]
