---
- name: create user {{ user }}
  hosts: all
  vars:
    user: alice
  tasks:
  - name: check user
    ansible.builtin.command: id {{ user }}
    register: iduser
  - name:
    debug:
      var: iduser

  - name: before check
    fail:
      msg: user already exists
    when: iduser["rc"] == 0
  - name: add user {{ user }}
    ansible.builtin.command: 
      cmd: useradd {{ user }}
    register: user_out



