---
- name: show lists also known as arrays
  hosts: ansible-node-01.deldel.lan
  vars_files:
    - users-list
  tasks:
    - name: print array values
      debug:
        msg: "User {{ item.username }} has homedirectory {{ item.homedir }} and shell {{ item.shell }}"
      loop: "{{ users }}"
    - name: print the second array value
      debug:
        msg: the second item is {{ users[1] }} 
