---
- name: test register
  hosts: all
  tasks:
  - shell: cat /etc/passwd
    register: passwd_contents
  - debug: 
      var: "passwd_contents"
  - debug:
      msg: the status of the command is {{ passwd_contents["rc"] }}
